# Generated by Django 6.1.1 on 2026-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('technology_domain', models.CharField(db_index=True, max_length=100)),
                ('assignee', models.CharField(max_length=150)),
                ('filing_year', models.PositiveIntegerField(db_index=True)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
            ],
            options={
                'ordering': ['-filing_year', '-citation_count'],
                'indexes': [models.Index(fields=['technology_domain', 'filing_year'], name='trends_pate_technol_e70ef4_idx')],
            },
        ),
    ]
